print('This is a sample python script')
name= input("what is your name?")
phone=input('Phone =')
print(name)
adrss=input('Adress-->')
city=input('City')
state=input('State')
print(adrss)
print(city)
print(state)